// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "GaAdmin/internal/logic/auth"
	_ "GaAdmin/internal/logic/context"
	_ "GaAdmin/internal/logic/oauth"
	_ "GaAdmin/internal/logic/org"
	_ "GaAdmin/internal/logic/session"
	_ "GaAdmin/internal/logic/sms"
	_ "GaAdmin/internal/logic/user"
)
