// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AuthRule is the golang structure of table auth_rule for DAO operations like Where/Data.
type AuthRule struct {
	g.Meta    `orm:"table:auth_rule, do:true"`
	Id        interface{} // ID
	MenuId    interface{} // 菜单ID
	Title     interface{} // 标题
	Path      interface{} // 规则URL
	Method    interface{} // 请求方法
	Condition interface{} // 条件
	Remark    interface{} // 备注
	Status    interface{} // 状态
	Weigh     interface{} // 权重
	CreateAt  *gtime.Time // 创建日期
	UpdateAt  *gtime.Time // 更新日期
}
