// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Org is the golang structure of table org for DAO operations like Where/Data.
type Org struct {
	g.Meta          `orm:"table:org, do:true"`
	Id              interface{} // ID
	Name            interface{} // 名称
	Phone           interface{} // 电话
	Address         interface{} // 地址
	CertificatesUrl interface{} // 证件
	CertificatesNo  interface{} // 证件号码
	Status          interface{} // 状态
	CreateAt        *gtime.Time // 创建日期
	UpdateAt        *gtime.Time // 更新日期
}
