// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// OrgDepartment is the golang structure of table org_department for DAO operations like Where/Data.
type OrgDepartment struct {
	g.Meta   `orm:"table:org_department, do:true"`
	Id       interface{} // ID
	ParentId interface{} // 父ID
	Title    interface{} // 标题
	Status   interface{} // 状态
	Weigh    interface{} // 权重
	CreateAt *gtime.Time // 创建日期
	UpdateAt *gtime.Time // 修改日期
}
