// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SecurityAnswer is the golang structure of table security_answer for DAO operations like Where/Data.
type SecurityAnswer struct {
	g.Meta   `orm:"table:security_answer, do:true"`
	Id       interface{} // ID
	UserId   interface{} // 用户ID
	Question interface{} // 问题
	Content  interface{} // 内容
	CreateAt *gtime.Time // 创建日期
}
