// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysConfig is the golang structure of table sys_config for DAO operations like Where/Data.
type SysConfig struct {
	g.Meta  `orm:"table:sys_config, do:true"`
	Id      interface{} // ID
	Name    interface{} // 名称
	Title   interface{} // 标题
	Type    interface{} // 类型
	Content interface{} // 内容
	Rule    interface{} // 验证规则
}
