// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// UserRoles is the golang structure of table user_roles for DAO operations like Where/Data.
type UserRoles struct {
	g.Meta  `orm:"table:user_roles, do:true"`
	UserId  interface{} // 用户ID
	GroupId interface{} // 用户组ID
}
