// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// UserAccess is the golang structure of table user_access for DAO operations like Where/Data.
type UserAccess struct {
	g.Meta     `orm:"table:user_access, do:true"`
	UserId     interface{} // 用户ID
	AuthRoleId interface{} // 权限角色ID
}
