// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserGroup is the golang structure of table user_group for DAO operations like Where/Data.
type UserGroup struct {
	g.Meta   `orm:"table:user_group, do:true"`
	Id       interface{} // ID
	ParentId interface{} // 父ID
	Name     interface{} // 名称
	Title    interface{} // 标题
	Status   interface{} // 状态
	Weigh    interface{} // 权重
	CreateAt *gtime.Time // 创建日期
	UpdateAt *gtime.Time // 修改日期
}
