// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SecurityAnswerDao is the data access object for table security_answer.
type SecurityAnswerDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns SecurityAnswerColumns // columns contains all the column names of Table for convenient usage.
}

// SecurityAnswerColumns defines and stores column names for table security_answer.
type SecurityAnswerColumns struct {
	Id       string // ID
	UserId   string // 用户ID
	Question string // 问题
	Content  string // 内容
	CreateAt string // 创建日期
}

//  securityAnswerColumns holds the columns for table security_answer.
var securityAnswerColumns = SecurityAnswerColumns{
	Id:       "id",
	UserId:   "user_id",
	Question: "question",
	Content:  "content",
	CreateAt: "create_at",
}

// NewSecurityAnswerDao creates and returns a new DAO object for table data access.
func NewSecurityAnswerDao() *SecurityAnswerDao {
	return &SecurityAnswerDao{
		group:   "default",
		table:   "security_answer",
		columns: securityAnswerColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SecurityAnswerDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SecurityAnswerDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SecurityAnswerDao) Columns() SecurityAnswerColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SecurityAnswerDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SecurityAnswerDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SecurityAnswerDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
