// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SecurityQuestionDao is the data access object for table security_question.
type SecurityQuestionDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns SecurityQuestionColumns // columns contains all the column names of Table for convenient usage.
}

// SecurityQuestionColumns defines and stores column names for table security_question.
type SecurityQuestionColumns struct {
	Id       string // ID
	Title    string // 标题
	CreateAt string // 创建日期
}

//  securityQuestionColumns holds the columns for table security_question.
var securityQuestionColumns = SecurityQuestionColumns{
	Id:       "id",
	Title:    "title",
	CreateAt: "create_at",
}

// NewSecurityQuestionDao creates and returns a new DAO object for table data access.
func NewSecurityQuestionDao() *SecurityQuestionDao {
	return &SecurityQuestionDao{
		group:   "default",
		table:   "security_question",
		columns: securityQuestionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SecurityQuestionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SecurityQuestionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SecurityQuestionDao) Columns() SecurityQuestionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SecurityQuestionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SecurityQuestionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SecurityQuestionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
