// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"GaAdmin/internal/model"
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type IOauth interface {
	Authorization(ctx context.Context, subject string, issueRoles []string) (*model.TokenOutput, error)
	RefreshAuthorization(ctx context.Context, ticket string) (*model.TokenOutput, error)
	ValidAuthorization(r *ghttp.Request) (g.Map, error)
	CheckPath(r *ghttp.Request, issueRoles []string) (bool, error)
	SavePolicy(ctx context.Context) error
}

var localOauth IOauth

func Oauth() IOauth {
	if localOauth == nil {
		panic("implement not found for interface IOauth, forgot register?")
	}
	return localOauth
}

func RegisterOauth(i IOauth) {
	localOauth = i
}
