// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"GaAdmin/internal/model"
	"GaAdmin/internal/model/entity"
	"context"
)

type IOrg interface {
	CreateMember(ctx context.Context, in *model.OrgMemberCreateInput) (*entity.OrgMember, error)
	GetMember(ctx context.Context, memberId uint) (*entity.OrgMember, error)
	UpdateMember(ctx context.Context, in *model.OrgMemberUpdateInput) (*entity.OrgMember, error)
	DeleteMember(ctx context.Context, id uint) error
	GetMemberPage(ctx context.Context, in *model.Page) (*model.OrgMemberPageOutput, error)
	CreateOrg(ctx context.Context, in *model.OrgCreateInput) (*entity.Org, error)
	GetOrg(ctx context.Context, orgId uint) (*entity.Org, error)
	UpdateOrg(ctx context.Context, in *model.OrgUpdateInput) (*entity.Org, error)
	DeleteOrg(ctx context.Context, id uint) error
	GetOrgPage(ctx context.Context, in *model.Page) (*model.OrgPageOutput, error)
}

var localOrg IOrg

func Org() IOrg {
	if localOrg == nil {
		panic("implement not found for interface IOrg, forgot register?")
	}
	return localOrg
}

func RegisterOrg(i IOrg) {
	localOrg = i
}
