// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalAuthRoleAccessDao is internal type for wrapping internal DAO implements.
type internalAuthRoleAccessDao = *internal.AuthRoleAccessDao

// authRoleAccessDao is the data access object for table auth_role_access.
// You can define custom methods on it to extend its functionality as you wish.
type authRoleAccessDao struct {
	internalAuthRoleAccessDao
}

var (
	// AuthRoleAccess is globally public accessible object for table auth_role_access operations.
	AuthRoleAccess = authRoleAccessDao{
		internal.NewAuthRoleAccessDao(),
	}
)

// Fill with you ideas below.
