// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalAuthAccessDao is internal type for wrapping internal DAO implements.
type internalAuthAccessDao = *internal.AuthAccessDao

// authAccessDao is the data access object for table auth_access.
// You can define custom methods on it to extend its functionality as you wish.
type authAccessDao struct {
	internalAuthAccessDao
}

var (
	// AuthAccess is globally public accessible object for table auth_access operations.
	AuthAccess = authAccessDao{
		internal.NewAuthAccessDao(),
	}
)

// Fill with you ideas below.
