// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalAuthMenuDao is internal type for wrapping internal DAO implements.
type internalAuthMenuDao = *internal.AuthMenuDao

// authMenuDao is the data access object for table auth_menu.
// You can define custom methods on it to extend its functionality as you wish.
type authMenuDao struct {
	internalAuthMenuDao
}

var (
	// AuthMenu is globally public accessible object for table auth_menu operations.
	AuthMenu = authMenuDao{
		internal.NewAuthMenuDao(),
	}
)

// Fill with you ideas below.
