// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalAuthRoleDao is internal type for wrapping internal DAO implements.
type internalAuthRoleDao = *internal.AuthRoleDao

// authRoleDao is the data access object for table auth_role.
// You can define custom methods on it to extend its functionality as you wish.
type authRoleDao struct {
	internalAuthRoleDao
}

var (
	// AuthRole is globally public accessible object for table auth_role operations.
	AuthRole = authRoleDao{
		internal.NewAuthRoleDao(),
	}
)

// Fill with you ideas below.
