// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalOrgMemberDao is internal type for wrapping internal DAO implements.
type internalOrgMemberDao = *internal.OrgMemberDao

// orgMemberDao is the data access object for table org_member.
// You can define custom methods on it to extend its functionality as you wish.
type orgMemberDao struct {
	internalOrgMemberDao
}

var (
	// OrgMember is globally public accessible object for table org_member operations.
	OrgMember = orgMemberDao{
		internal.NewOrgMemberDao(),
	}
)

// Fill with you ideas below.
