// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalOrgDepartmentDao is internal type for wrapping internal DAO implements.
type internalOrgDepartmentDao = *internal.OrgDepartmentDao

// orgDepartmentDao is the data access object for table org_department.
// You can define custom methods on it to extend its functionality as you wish.
type orgDepartmentDao struct {
	internalOrgDepartmentDao
}

var (
	// OrgDepartment is globally public accessible object for table org_department operations.
	OrgDepartment = orgDepartmentDao{
		internal.NewOrgDepartmentDao(),
	}
)

// Fill with you ideas below.
