// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalSecurityQuestionDao is internal type for wrapping internal DAO implements.
type internalSecurityQuestionDao = *internal.SecurityQuestionDao

// securityQuestionDao is the data access object for table security_question.
// You can define custom methods on it to extend its functionality as you wish.
type securityQuestionDao struct {
	internalSecurityQuestionDao
}

var (
	// SecurityQuestion is globally public accessible object for table security_question operations.
	SecurityQuestion = securityQuestionDao{
		internal.NewSecurityQuestionDao(),
	}
)

// Fill with you ideas below.
