// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalSecurityAnswerDao is internal type for wrapping internal DAO implements.
type internalSecurityAnswerDao = *internal.SecurityAnswerDao

// securityAnswerDao is the data access object for table security_answer.
// You can define custom methods on it to extend its functionality as you wish.
type securityAnswerDao struct {
	internalSecurityAnswerDao
}

var (
	// SecurityAnswer is globally public accessible object for table security_answer operations.
	SecurityAnswer = securityAnswerDao{
		internal.NewSecurityAnswerDao(),
	}
)

// Fill with you ideas below.
