// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GaAdmin/internal/dao/internal"
)

// internalUserGroupAccessDao is internal type for wrapping internal DAO implements.
type internalUserGroupAccessDao = *internal.UserGroupAccessDao

// userGroupAccessDao is the data access object for table user_group_access.
// You can define custom methods on it to extend its functionality as you wish.
type userGroupAccessDao struct {
	internalUserGroupAccessDao
}

var (
	// UserGroupAccess is globally public accessible object for table user_group_access operations.
	UserGroupAccess = userGroupAccessDao{
		internal.NewUserGroupAccessDao(),
	}
)

// Fill with you ideas below.
