// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AuthRoleAccess is the golang structure for table auth_role_access.
type AuthRoleAccess struct {
	RoleId uint `json:"roleId" ` // 角色ID
	RuleId uint `json:"ruleId" ` // 规则ID
}
