// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AuthAccess is the golang structure for table auth_access.
type AuthAccess struct {
	Type   string `json:"type"   ` // 类型
	RuleId uint   `json:"ruleId" ` // 规则ID
}
