// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Org is the golang structure for table org.
type Org struct {
	Id              uint        `json:"id"              ` // ID
	Name            string      `json:"name"            ` // 名称
	Phone           string      `json:"phone"           ` // 电话
	Address         string      `json:"address"         ` // 地址
	CertificatesUrl string      `json:"certificatesUrl" ` // 证件
	CertificatesNo  string      `json:"certificatesNo"  ` // 证件号码
	Status          string      `json:"status"          ` // 状态
	CreateAt        *gtime.Time `json:"createAt"        ` // 创建日期
	UpdateAt        *gtime.Time `json:"updateAt"        ` // 更新日期
}
