// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SecurityAnswer is the golang structure for table security_answer.
type SecurityAnswer struct {
	Id       uint        `json:"id"       ` // ID
	UserId   uint        `json:"userId"   ` // 用户ID
	Question string      `json:"question" ` // 问题
	Content  string      `json:"content"  ` // 内容
	CreateAt *gtime.Time `json:"createAt" ` // 创建日期
}
