// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SecurityQuestion is the golang structure for table security_question.
type SecurityQuestion struct {
	Id       uint        `json:"id"       ` // ID
	Title    string      `json:"title"    ` // 标题
	CreateAt *gtime.Time `json:"createAt" ` // 创建日期
}
