// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysConfig is the golang structure for table sys_config.
type SysConfig struct {
	Id      uint   `json:"id"      ` // ID
	Name    string `json:"name"    ` // 名称
	Title   string `json:"title"   ` // 标题
	Type    string `json:"type"    ` // 类型
	Content string `json:"content" ` // 内容
	Rule    string `json:"rule"    ` // 验证规则
}
