// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserAccess is the golang structure for table user_access.
type UserAccess struct {
	UserId     uint `json:"userId"     ` // 用户ID
	AuthRoleId uint `json:"authRoleId" ` // 权限角色ID
}
