// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserGroupAccess is the golang structure for table user_group_access.
type UserGroupAccess struct {
	GroupId    uint `json:"groupId"    ` // 用户组ID
	AuthRuleId uint `json:"authRuleId" ` // 权限规则ID
}
