// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserRoles is the golang structure for table user_roles.
type UserRoles struct {
	UserId  uint `json:"userId"  ` // 用户ID
	GroupId uint `json:"groupId" ` // 用户组ID
}
